#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rosdistro
Version  : 0.6.9
Release  : 2
URL      : https://files.pythonhosted.org/packages/16/29/8ba39bfeb2d1e5c5a8ce37c814ed673eb0f1be2a127b44e3eec39475f9fd/rosdistro-0.6.9.tar.gz
Source0  : https://files.pythonhosted.org/packages/16/29/8ba39bfeb2d1e5c5a8ce37c814ed673eb0f1be2a127b44e3eec39475f9fd/rosdistro-0.6.9.tar.gz
Summary  : A tool to work with rosdistro files
Group    : Development/Tools
License  : MIT
Requires: rosdistro-bin
Requires: rosdistro-python3
Requires: rosdistro-python
Requires: PyYAML
Requires: catkin_pkg
Requires: rospkg
Requires: setuptools
BuildRequires : buildreq-distutils3
BuildRequires : catkin_pkg
BuildRequires : rospkg

%description
rosdistro
=====
Code & tickets
--------------
+----------------------+-----------------------------------------------------------+
| rosdistro            | http://github.com/ros-infrastructure/rosdistro            |
+----------------------+-----------------------------------------------------------+
| Issues               | http://github.com/ros-infrastructure/rosdistro/issues     |
+----------------------+-----------------------------------------------------------+

%package bin
Summary: bin components for the rosdistro package.
Group: Binaries

%description bin
bin components for the rosdistro package.


%package python
Summary: python components for the rosdistro package.
Group: Default
Requires: rosdistro-python3

%description python
python components for the rosdistro package.


%package python3
Summary: python3 components for the rosdistro package.
Group: Default
Requires: python3-core

%description python3
python3 components for the rosdistro package.


%prep
%setup -q -n rosdistro-0.6.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533782895
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rosdistro_build_cache
/usr/bin/rosdistro_freeze_source
/usr/bin/rosdistro_migrate_to_rep_141
/usr/bin/rosdistro_migrate_to_rep_143
/usr/bin/rosdistro_reformat

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
